### ISSUE TITLE
Add a single AA boost chip / LDO regulator

### ISSUE THREAD

**Issue by JohnOH** [tht/bp-extender#3]
BP is a nice size for AA battery operation.
The existing regulator on the BP is frowned upon as being inefficient.

**Comment by JohnOH** [comment]
Perhaps a LiPo charger instead, to act as  a UPS for an AC connected device.

**Comment by tht** [comment]
The current *extender* is designed to be used on a breadboard. For standalone use there are some different requirements. For example we don't have to be on top of the BP and the size (specially the width) does not matter that much.

If this board works, we should start to collect requirements for another module - optimized for standalone use. AA power, LiPo charger and also easily accessible SPI and I2C ports are perfect candidates. I'll add a *label* to make sure de don't loose these ideas.

**Comment by tht** [comment]
I will close this issue for now as this board has a different use-case and the BP is not optimized for low-power (battery) operation.
