### ISSUE TITLE
Fix offset of rev1 board

### ISSUE THREAD

**Issue by tht** [tht/bp-extender#8]
The board is off-center – looks like 1.27mm. Should be fixed in rev2.

**Comment by jcw** [comment]
There seem to be slightly different variants of the BP out there, see images.

![dsc_5689](https://cloud.githubusercontent.com/assets/148955/22704866/964433f8-ed69-11e6-9756-c31707866eb1.jpg)
![dsc_5690](https://cloud.githubusercontent.com/assets/148955/22704868/965d3b64-ed69-11e6-8cfd-e35dd8628bc0.jpg)
![dsc_5691](https://cloud.githubusercontent.com/assets/148955/22704867/965d2520-ed69-11e6-9ae8-8ece3ff3e735.jpg)
![dsc_5692](https://cloud.githubusercontent.com/assets/148955/22704869/9661bdec-ed69-11e6-9406-907c3c530839.jpg)

**Comment by JohnOH** [comment]
I think you may have a red pill layout on a blue PCB. I note that the USB connector is surface mounted rather than through the board. See http://www.stm32duino.com/viewtopic.php?t=117

**Comment by JohnOH** [comment]
![dscf2035](https://cloud.githubusercontent.com/assets/2646973/22713131/2276f12a-ed7f-11e6-822c-849af317f9fe.JPG)
![dscf2036](https://cloud.githubusercontent.com/assets/2646973/22713132/227dac54-ed7f-11e6-9a8c-9e5b82429f94.JPG)

I have fourteen units bought in two or three at a time from various chinese sources. They all have the the USB shield attached through the PCB rather than surface mount only.

**Comment by tht** [comment]
Same here… about 10 boards, bought from two different sellers. All do have the USB socket mounted through the board. So this is the big difference, good to know. Thanks for investigating this issue. I will add a note in the `README.md`.

Update: 216f1a227db5abbf6d78fd1705c14e1d4db32a70 adds the comment to the readme file.

**Comment by jcw** [comment]
Just to understand: my impression is that there is no difference, apart from appearance/dimensions?

**Comment by jcw** [comment]
As I mentioned to Thomas in a private chat, I'm going to call mine the "twist and shout" setup - 'cause it needs a lot of twisting and shouting to set up :) - haven't tried it out yet, it'll probably be 100% fine.

**Comment by tht** [comment]
Your's is the one with *personality* :)

There are quite a few differences on these two boards. Labels are different, the USB connector is mounted different and the 2x03 header is not at the same place on the board. I think the board itself should be the same dimension when looking at your pictures. According to http://www.stm32duino.com/viewtopic.php?t=117 there is more - like different LDOs and resistor/cap values.

**Comment by JohnOH** [comment]
Perhaps we could physically snip off the four outer pins from the Blue Pill 2x03 header retaining only the path to the relevant GPIO pins. We could then drive these pins with 3v/GND derived from elsewhere on the Expander PCB. This would offer the opportunity of having four holes passing through the expander with connections in parallel such that a Red Pill and a Blue Pill could both use the expander PCB soldering the appropriate two pins for the particular board.

**Comment by tht** [comment]
Thats a great idea John. I'll most likely go this way for rev2 of the board. So it *should* fit on top of all red- and blue pills in red and blue coats.

3.3V and GND are available right next to these pins, so no problem to get these levels from other pins.

Only disadvantage is the loss in rigidity but I don't think this is a big issue. I will also try to get hold of some long pin headers. Just snip off the top of these long headers where there is no hole in the extender board and connect all the others through.

**Comment by tht** [comment]
I still have to fix the reset button's footprint and check if it's possible to add an U.FL connector but the offset *should* be fixed and this one is compatible with *pills* in all different colours.
![bildschirmfoto 2017-02-11 um 13 11 43](https://cloud.githubusercontent.com/assets/2557225/22853620/cdfd54b0-f05b-11e6-8234-ee37c1796bf7.png)
I've added some holes which aren't absolutely necessary. This should make it easier to mount it on extra long headers pushed through the BP **and** this adds-on board.
